### ISSUE TITLE
ConfigureDT stops processing DTs after getting an exception due to a locked DT 

### ISSUE THREAD

**Issue by rscher** [ODMDev/decision-center-api-samples#3]
If there are locked DT's , throws exception and appears to stop processing

```
$  /opt/IBM/ODM893/jdk/bin/java  -cp "/opt/IBM/ODM893/teamserver/lib/*:/opt/IBM/ODM893/teamserver/lib/eclipse_plugins/*:" com.ibm.odm.tools.ConfigureDT -username rtsAdmin -password rtsAdmin -url http://zzxr760    1.msci.svl.ibm.com:9084/decisioncenter   -dataSource jdbc/ilogDataSource  -decisionService  ,serviceName -branch  MAIN   -autoResize false
Configure DT properties in decision service 'PremierDiscountRules_MainRuleFlow'
Nov 30, 2021 6:02:36 PM com.ibm.rules.decisioncenter.remoting.internal.RemoteSessionHttpExecutorBuilder log
INFO: {"url":"http://zzxr7601.msci.svl.ibm.com:9084/decisioncenter","datasource":"jdbc/ilogDataSource","username":"rtsAdmin","message":"Sign in successfully","date":"November 30, 2021 6:02:36 PM"}
Nov 30, 2021 6:02:36 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@24bb3131: startup date [Tue Nov 30 18:02:36 PST 2021]; root of context hierarchy
Nov 30, 2021 6:02:36 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [ilog/rules/teamserver/client/client-applicationContext.xml]
Nov 30, 2021 6:02:37 PM com.ibm.rules.decisioncenter.remoting.internal.RemoteSessionHttpExecutorBuilder log
INFO: {"url":"http://zzxr7601.msci.svl.ibm.com:9084/decisioncenter","datasource":"jdbc/ilogDataSource","username":"rtsAdmin","message":"Sign in successfully","date":"November 30, 2021 6:02:37 PM"}
Nov 30, 2021 6:02:37 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@a3bfabf1: startup date [Tue Nov 30 18:02:37 PST 2021]; root of context hierarchy
Nov 30, 2021 6:02:37 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [ilog/rules/teamserver/client/client-applicationContext.xml]
-- skipping lines --
Updating 489 DT in serviceName in branch MAIN
ilog.rules.teamserver.model.IlrObjectLockedException: GBRDR0031E: The element 'rule1' of type 'decision table' is already locked by user user1
        at ilog.rules.teamserver.ejb.service.IlrSessionFacadeImpl.commit(IlrSessionFacadeImpl.java:1436)
        at ilog.rules.teamserver.ejb.service.IlrSessionFacadeImpl.commit(IlrSessionFacadeImpl.java:1131)
.

\]

 Deleted the entries , ran configureDT cmd again and it appears to continue processing .

**Comment by alainrobert** [comment]
fixed in v0.0.3
