### ISSUE TITLE
configure-dt-0.0.5.jar  times out  when processing many (thousands of) DT's  within a branch 

### ISSUE THREAD

**Issue by rscher** [ODMDev/decision-center-api-samples#6]
As discussed in mtg,  need  another change to configure-dt to handle cust scenario of ~10,000 DTs  within a branch.
under these conditions, cust gets  Read timed out exception-

C:\Program Files\IBM\ODM892\jdk\bin>java -cp "C:/Program Files/IBM/ODM892/teamserver/lib/*;C:/Program Files/IBM/ODM892/teamserver/lib/eclipse_plugins/*;" com.ibm.odm.tools.ConfigureDT -username ***** -password ***** -url http://dwauslodmap01.app.dev.hcscint.net:9080/decisioncenter -dataSource jdbc/ilogDataSource -decisionService PremierDiscountRules_MainRuleFlow -branch TS006207114 -autoResize false -unhideColumns true
Configure DT properties in decision service 'PremierDiscountRules_MainRuleFlow'
..
..
Updating 9280 DT in PremierDiscountRules_Rate in branch TS006207114
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [http://dwauslodmap01.app.dev.hcscint.net:9080/decisioncenter/remoting/session?__dcsid=4f0e11bbf7ecd8d9906c2483d50650c3]; nested exception is java.net.SocketTimeoutException: Read timed out
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:226)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy1.commit(Unknown Source)
        at ilog.rules.teamserver.model.impl.IlrAbstractSession.commit(IlrAbstractSession.java:1319)
        at ilog.rules.teamserver.model.impl.IlrAbstractCachingSession.commit(IlrAbstractCachingSession.java:149)
        at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at ilog.rules.teamserver.client.IlrSessionInvocationHandler.invoke(IlrSessionInvocationHandler.java:43)
        at com.sun.proxy.$Proxy2.commit(Unknown Source)
        at com.ibm.odm.tools.ConfigureDT.updateDT(ConfigureDT.java:197)
        at com.ibm.odm.tools.ConfigureDT.updateBranch(ConfigureDT.java:164)
        at com.ibm.odm.tools.ConfigureDT.updateBranch(ConfigureDT.java:169)
        at com.ibm.odm.tools.ConfigureDT.execute(ConfigureDT.java:114)
        at ilog.rules.teamserver.client.internal.BRMServerClient.doExecute(BRMServerClient.java:38)
        at com.ibm.odm.tools.ConfigureDT.main(ConfigureDT.java:264)
Caused by: java.net.SocketTimeoutException: Read timed out
.

Full trace here:   https://gist.github.com/rscher/ae0983cb87784d86ac4edaa9762f1ce4

**Comment by alainrobert** [comment]
refactor code to not keep the session for too long and open a new one when needed
